# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bop.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bop.BopRequest" do
    optional :url, :string, 1
  end
  add_message "bop.BopResponse" do
    optional :url, :string, 1
  end
end

module Bop
  BopRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bop.BopRequest").msgclass
  BopResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bop.BopResponse").msgclass
end
