# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bop.proto for package 'bop'

require 'grpc'
require 'bop_pb'

module Bop
  module BopService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bop.BopService'

      rpc :bop_it, BopRequest, BopResponse
    end

    Stub = Service.rpc_stub_class
  end
end
